# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(default=-99, on_delete=django.db.models.deletion.CASCADE, to='users.Cohort'),
            preserve_default=False,
        ),
    ]
